pipeline {
    agent { label 'master'}

        stages {
 
            stage ('test') {
                steps {
                  dir("jenkins-leo-demo/build_java"){
                        echo "mvn clean compile test"
                  }
                   
                   
                }
            }

            stage ('Build application') {
                steps {
                    dir("jenkins-leo-demo/build_java"){

                        sh "mvn -f pom.xml clean install -Dmaven.test.skip=true"
                        sh "tree"
                    }   
                }
            }
  
            stage ('Create docker image') {
                steps {
                 echo "creando docker"
                }

            }
        }
}
